# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0004_auto_20170520_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='session',
            new_name='sem',
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='course_code',
            field=models.CharField(blank=True, help_text='Eg. APL100', max_length=6),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_exam',
            field=models.CharField(blank=True, help_text='Eg. minor1', max_length=10),
        ),
    ]
