# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0008_auto_20170520_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='typ',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='studapp.Minor1'),
        ),
    ]
