# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0009_auto_20170520_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='typ',
        ),
    ]
