# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0010_remove_document_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='paper_real',
            field=models.FileField(default='test', upload_to=b''),
            preserve_default=False,
        ),
    ]
