# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0011_other_paper_real'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='other',
            name='paper',
        ),
    ]
