# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0013_auto_20170520_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='major',
            old_name='paper_real',
            new_name='paper',
        ),
        migrations.RenameField(
            model_name='minor1',
            old_name='paper_real',
            new_name='paper',
        ),
        migrations.RenameField(
            model_name='minor2',
            old_name='paper_real',
            new_name='paper',
        ),
        migrations.RenameField(
            model_name='other',
            old_name='paper_real',
            new_name='paper',
        ),
    ]
