# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0014_auto_20170520_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default='add', max_length=3),
            preserve_default=False,
        ),
    ]
