# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-11 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0017_auto_20170530_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, help_text='any information about the uploaded document that can be seen by the other users - topic, difficulty level or even the professor!', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='course_code',
            field=models.CharField(blank=True, help_text='e.g. APL100', max_length=6),
        ),
        migrations.AlterField(
            model_name='document',
            name='sem',
            field=models.CharField(blank=True, help_text='e.g. 1', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_exam',
            field=models.CharField(blank=True, help_text='e.g. minor1/Tut/Book', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.CharField(blank=True, help_text='e.g. 2016-17', max_length=20),
        ),
    ]
