# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-11 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0018_auto_20170811_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
