# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-11 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0019_major_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='minor1',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='minor2',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='other',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
