# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import functools
import studapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0020_auto_20170811_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=functools.partial(studapp.models._update_filename, *(), **{b'path': 'unapproved_documents/'})),
        ),
    ]
