# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0020_auto_20170811_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.FileField(upload_to=b'')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studapp.Course_code')),
            ],
            options={
                'ordering': ('course',),
            },
        ),
    ]
