# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0021_auto_20170902_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='major',
            name='description',
        ),
        migrations.RemoveField(
            model_name='minor1',
            name='description',
        ),
        migrations.RemoveField(
            model_name='minor2',
            name='description',
        ),
        migrations.RemoveField(
            model_name='other',
            name='description',
        ),
    ]
