# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0021_listfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListFiles',
            new_name='Listfile',
        ),
    ]
