# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0022_auto_20170820_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfile',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studapp.Other'),
        ),
    ]
