# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0023_auto_20170820_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listfile',
            name='paper',
        ),
        migrations.AddField(
            model_name='listfile',
            name='paper_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listfile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studapp.Course_code'),
        ),
    ]
