# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0023_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='track',
            name='object_id',
        ),
        migrations.AddField(
            model_name='track',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studapp.Course_code'),
        ),
        migrations.AddField(
            model_name='track',
            name='pagehits',
            field=models.IntegerField(null=True),
        ),
    ]
