# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0024_auto_20170822_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listfile',
            options={'ordering': ('code',)},
        ),
        migrations.RenameField(
            model_name='listfile',
            old_name='course',
            new_name='code',
        ),
    ]
