# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0024_auto_20170909_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='course',
        ),
        migrations.AddField(
            model_name='course_code',
            name='pagehits',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
