# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0025_auto_20170909_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_code',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='studapp.Department'),
        ),
        migrations.AlterField(
            model_name='major',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='studapp.Course_code'),
        ),
        migrations.AlterField(
            model_name='minor1',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minors1', to='studapp.Course_code'),
        ),
        migrations.AlterField(
            model_name='minor2',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minors2', to='studapp.Course_code'),
        ),
        migrations.AlterField(
            model_name='other',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='others', to='studapp.Course_code'),
        ),
    ]
