# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0025_auto_20170822_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listfile',
            options={},
        ),
        migrations.RenameField(
            model_name='listfile',
            old_name='code',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='listfile',
            name='paper_name',
        ),
    ]
