# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0026_auto_20170911_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_code',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studapp.Department'),
        ),
        migrations.AlterField(
            model_name='major',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studapp.Course_code'),
        ),
        migrations.AlterField(
            model_name='minor1',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studapp.Course_code'),
        ),
        migrations.AlterField(
            model_name='minor2',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studapp.Course_code'),
        ),
        migrations.AlterField(
            model_name='other',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studapp.Course_code'),
        ),
    ]
