# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0026_auto_20170822_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listfile',
            old_name='course',
            new_name='coursecode',
        ),
    ]
