# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0027_auto_20170822_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='listfile',
            name='other_papers',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
